#!/bin/bash

set -e



strtrim() {
	echo $(cat - | perl -pe 's/^[\ ]+//g; s/[\ ]+$//g')
}

stripextrawhites() {
	echo $(cat - | perl -pe 's/[\ ]+/ /g')
}

removenewlines() {
    echo $(cat - | perl -pe 's/\n/\ /g')
}

stripwhites() {
    echo $(cat - | perl -pe 's/[\n\ ]//g')
}

stripunsafe() {
	echo $(cat - | perl -pe 's/[^A-Za-z0-9\ \-\?]//g' | stripextrawhites)
}

camelize_old() {
    echo $(cat - | sed -r 's/^(.)/\ \1/; s/[\ ]+/ /g; s/\ ([a-zA-Z\-]+)/\ \L\u\1/g; s/^[\ ]+//g; s/[\ ]+$//g; s/\ /_/g')
}

camelize() {
	echo $(cat - | perl -pe 's/^(.)/\ \1/; s/[\ ]([a-zA-Z]+)/\ \L\u\1/g; s/[\-]([a-zA-Z]+)/\-\L\u\1/g; s/^[\ ]//')
}

if [[ $# -ne 1 ]]
then
    echo "usage: pubrename [pdf name]"
    exit -1
fi

evince "$1" 2>/dev/null &
pid=$!

printf "PLEASE WRITE THE AUTHOR: "
read author_raw
author=$(echo "$author_raw" | stripunsafe | strtrim | stripextrawhites | camelize | perl -pe 's/\ /_/g')
author2=$(echo "$author_raw" | stripunsafe | strtrim | stripextrawhites | camelize | perl -pe 's/\ /\,\ /g')

###

printf "PLEASE WRITE THE YEAR: "
read year_raw

year=$(echo "$year_raw" | perl -pe 's/[^0-9]//g')

###

printf "PLEASE PASTE THE TITLE\n"
TMPFILE=$(mktemp)
sleep 1
nano "$TMPFILE"
title_raw=$(cat "$TMPFILE")
rm "$TMPFILE"

title=$(echo "$title_raw" | removenewlines | stripunsafe | strtrim | stripextrawhites | camelize | perl -pe 's/\ /_/g')
title2=$(echo "$title_raw" | removenewlines | stripunsafe | strtrim | stripextrawhites | camelize)

fn_new="${year}__${author}__${title}.pdf"
fn_new2="${author2} (${year}) ${title2}.pdf"

kill $pid && echo "killing evince"

mv -v "$1" "$(dirname "$1")/$fn_new"
ln -srv "$(dirname "$1")/$fn_new" "$(dirname "$1")/$fn_new2"
